name: shared_state
description: Providing a shared state store ability for dart. With `shared_state_store`, developers can share state in one isolate easily and can be notified when state changed. Also, it can be a rescue for handle  complex package dependencies by DI.
version: 1.0.0
repository: https://github.com/Pikaurd/shared-state-dart

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
